import { OrganizationTomlEvidenceMigration1784795000000 } from '../1784795000000-OrganizationTomlEvidenceMigration.js';

describe('OrganizationTomlEvidenceMigration1784795000000', () => {
	let migration: OrganizationTomlEvidenceMigration1784795000000;
	let queryRunner: { isTransactionActive: boolean; query: jest.Mock };

	beforeEach(() => {
		migration = new OrganizationTomlEvidenceMigration1784795000000();
		queryRunner = { isTransactionActive: false, query: jest.fn() };
	});

	it('installs only online schema phases and resumable backfill state', async () => {
		await migration.up(queryRunner as never);

		const sql = queryRunner.query.mock.calls.join('\n');
		expect(migration.transaction).toBe(false);
		expect(sql).toContain("set lock_timeout = '2s'");
		expect(sql).toContain("set statement_timeout = '5min'");
		expect(sql).toContain('add column if not exists "tomlFetchResult"');
		expect(sql).toContain('check (');
		expect(sql).toContain('not valid');
		expect(sql).not.toContain('update "organization_measurement"');
		expect(sql).not.toContain('insert into "organization_toml_attempt" (');
		expect(sql).toContain(
			'create table if not exists "organization_toml_attempt"'
		);
		expect(sql).toContain('"sequence" bigint generated by default as identity');
		expect(sql).toContain('"scanRunId" text not null');
		expect(sql).toContain('"contentHash" char(64)');
		expect(sql).toContain(
			'create table if not exists "organization_toml_snapshot"'
		);
		expect(sql).toContain(
			'create table if not exists "organization_toml_backfill_progress"'
		);
		expect(sql).toContain(
			'create table if not exists "organization_toml_backfill_quarantine"'
		);
		expect(sql).toContain("'invalid_state', 'invalid_warnings'");
		expect(sql).toContain('check ("phase" = \'organizations\')');
		expect(sql).toContain('"latestSuccessAuthoritative" boolean');
		expect(sql).toContain('TlsCertificateVerificationDisabled');
		expect(sql).toContain('create index concurrently if not exists');
		expect(sql).not.toContain(
			'IDX_organization_measurement_toml_fetch_result_time'
		);
	});

	it('refuses a transaction even if a runner is misconfigured', async () => {
		queryRunner.isTransactionActive = true;
		await expect(migration.up(queryRunner as never)).rejects.toThrow(
			'must not run inside a transaction'
		);
		expect(queryRunner.query).not.toHaveBeenCalled();
	});

	it('repairs invalid concurrent indexes left by an interrupted attempt', async () => {
		queryRunner.query.mockImplementation((sql: string) =>
			sql.includes('select index_metadata.indisvalid')
				? [{ isValid: false }]
				: undefined
		);

		await migration.up(queryRunner as never);

		const sql = queryRunner.query.mock.calls.join('\n');
		expect(sql).toContain(
			'drop index concurrently if exists "IDX_organization_toml_attempt_observed"'
		);
	});

	it('removes the additive TOML evidence schema on rollback', async () => {
		queryRunner.isTransactionActive = true;
		await migration.down(queryRunner as never);

		const sql = queryRunner.query.mock.calls.join('\n');
		expect(sql).toContain('drop table if exists "organization_toml_snapshot"');
		expect(sql).toContain('drop table if exists "organization_toml_attempt"');
		expect(sql).toContain('drop column if exists "tomlEvidenceSequence"');
		expect(sql).toContain('drop column if exists "tomlFetchResult"');
	});
});
