export const historyArchiveCheckpointProofUpsertSql = `
	insert into "history_archive_checkpoint_proof" (
		"archiveUrl",
		"archiveUrlIdentity",
		"checkpointLedger",
		status,
		"proofVersion",
		"requiredObjectsComplete",
		"proofFactsComplete",
		"checkpointBucketListMatches",
		"transactionsMatch",
		"resultsMatch",
		"previousLedgersMatch",
		"bucketsVerified",
		"ledgerFactCount",
		"transactionFactCount",
		"resultFactCount",
		"expectedBucketCount",
		"verifiedBucketCount",
		"failedBucketCount",
		"missingBucketCount",
		"checkpointBucketListHash",
		"ledgerBucketListHash",
		"checkpointStateObjectRemoteId",
		"ledgerObjectRemoteId",
		"transactionsObjectRemoteId",
		"resultsObjectRemoteId",
		"scpObjectRemoteId",
		"failureKind",
		details,
		"evaluatedAt",
		"createdAt",
		"updatedAt"
	)
	select
		"archiveUrl",
		"archiveUrlIdentity",
		"checkpointLedger",
		status,
		5,
		required_objects_complete,
		proof_facts_complete,
		checkpoint_bucket_list_matches,
		transactions_match,
		results_match,
		previous_ledgers_match,
		buckets_verified,
		ledger_fact_count,
		transaction_fact_count,
		result_fact_count,
		expected_bucket_count,
		verified_bucket_count,
		failed_bucket_count,
		missing_bucket_count,
		checkpoint_bucket_list_hash,
		ledger_bucket_list_hash,
		"checkpointStateObjectRemoteId",
		"ledgerObjectRemoteId",
		"transactionsObjectRemoteId",
		"resultsObjectRemoteId",
		"scpObjectRemoteId",
		failure_kind,
		jsonb_build_object(
			'expectedLedgerCount', expected_ledger_count,
			'ledgerRawFactCount', ledger_raw_fact_count,
			'transactionRawFactCount', transaction_raw_fact_count,
				'resultRawFactCount', result_raw_fact_count,
				'predecessorMissing', predecessor_missing,
				'predecessorBoundaryValid', predecessor_boundary_valid,
			'scpEntryCount', scp_entry_count,
			'hasActiveObject', has_active,
			'hasFailedObject', has_failed,
			'expectsScp', expects_scp,
			'scpExpectationKnown', scp_expectation_known,
			'networkPassphrase', network_passphrase,
			'maxProtocolVersion', max_protocol_version,
			'failureErrorType', failure_error_type,
			'failureChannel', failure_channel,
			'failureChannels', coalesce(to_jsonb(failure_channels), '[]'::jsonb),
			'failureHttpStatus', failure_http_status,
			'objectFailures', coalesce(object_failures, '[]'::jsonb)
		),
		now(),
		now(),
		now()
	from finalized
	on conflict ("archiveUrlIdentity", "checkpointLedger")
	do update set
		"archiveUrl" = excluded."archiveUrl",
		status = excluded.status,
		"proofVersion" = excluded."proofVersion",
		"requiredObjectsComplete" = excluded."requiredObjectsComplete",
		"proofFactsComplete" = excluded."proofFactsComplete",
		"checkpointBucketListMatches" =
			excluded."checkpointBucketListMatches",
		"transactionsMatch" = excluded."transactionsMatch",
		"resultsMatch" = excluded."resultsMatch",
		"previousLedgersMatch" = excluded."previousLedgersMatch",
		"bucketsVerified" = excluded."bucketsVerified",
		"ledgerFactCount" = excluded."ledgerFactCount",
		"transactionFactCount" = excluded."transactionFactCount",
		"resultFactCount" = excluded."resultFactCount",
		"expectedBucketCount" = excluded."expectedBucketCount",
		"verifiedBucketCount" = excluded."verifiedBucketCount",
		"failedBucketCount" = excluded."failedBucketCount",
		"missingBucketCount" = excluded."missingBucketCount",
		"checkpointBucketListHash" = excluded."checkpointBucketListHash",
		"ledgerBucketListHash" = excluded."ledgerBucketListHash",
		"checkpointStateObjectRemoteId" =
			excluded."checkpointStateObjectRemoteId",
		"ledgerObjectRemoteId" = excluded."ledgerObjectRemoteId",
		"transactionsObjectRemoteId" =
			excluded."transactionsObjectRemoteId",
		"resultsObjectRemoteId" = excluded."resultsObjectRemoteId",
		"scpObjectRemoteId" = excluded."scpObjectRemoteId",
		"failureKind" = excluded."failureKind",
		details = excluded.details,
		"evaluatedAt" = excluded."evaluatedAt",
		"updatedAt" = now()
`;
