import type { MigrationInterface, QueryRunner } from 'typeorm';

export class OrganizationTomlEvidenceMigration1784795000000 implements MigrationInterface {
	readonly name = 'OrganizationTomlEvidenceMigration1784795000000';
	readonly transaction = false;

	public async up(queryRunner: QueryRunner): Promise<void> {
		if (queryRunner.isTransactionActive) {
			throw new Error(
				'Organization TOML online migration must not run inside a transaction'
			);
		}
		await queryRunner.query(`set lock_timeout = '2s'`);
		await queryRunner.query(`set statement_timeout = '5min'`);
		try {
			await queryRunner.query(`
				alter table "organization_measurement"
					add column if not exists "tomlFetchResult" text,
					add column if not exists "tomlEvidenceSequence" bigint,
					add column if not exists "scanRunId" text
			`);
			await queryRunner.query(`
				do $$
				begin
					if not exists (
						select 1 from pg_constraint
						where conname = 'CHK_organization_measurement_toml_fetch_result'
					) then
						alter table "organization_measurement" add constraint
							"CHK_organization_measurement_toml_fetch_result"
							check (
								"tomlFetchResult" is null or "tomlFetchResult" in (
									'not_attempted', 'success', 'failure'
								)
							) not valid;
					end if;
				end $$
			`);
			await queryRunner.query(`
				create table if not exists "organization_toml_content" (
					"hash" char(64) primary key,
					"byteLength" integer not null,
					"content" text not null,
					"createdAt" timestamptz not null default now(),
					constraint "CHK_organization_toml_content_hash"
						check ("hash" ~ '^[0-9a-f]{64}$')
				)
			`);
			await queryRunner.query(`
				create table if not exists "organization_toml_attempt" (
					"sequence" bigint generated by default as identity primary key,
					"organizationId" integer not null,
					"scanRunId" text not null,
					"observedAt" timestamptz not null,
					"result" text not null,
					"state" text not null,
					"warnings" jsonb not null default '[]'::jsonb,
					"authoritative" boolean not null default false,
					"contentHash" char(64),
					"source" text not null default 'network_scan',
					"createdAt" timestamptz not null default now(),
					constraint "FK_organization_toml_attempt_organization"
						foreign key ("organizationId") references "organization"(id)
						on delete cascade,
					constraint "FK_organization_toml_attempt_content"
						foreign key ("contentHash")
						references "organization_toml_content"("hash"),
					constraint "UQ_organization_toml_attempt_run"
						unique ("organizationId", "scanRunId"),
					constraint "UQ_organization_toml_attempt_success_provenance"
						unique (
							"organizationId", "sequence", "authoritative",
							"observedAt", "contentHash"
						),
					constraint "CHK_organization_toml_attempt_result"
						check ("result" in ('success', 'failure')),
					constraint "CHK_organization_toml_attempt_content"
						check (
							not "authoritative" or (
								"result" = 'success' and "contentHash" is not null and
								not (
									"warnings" ? 'TlsCertificateVerificationDisabled'
								)
							)
						),
					constraint "CHK_organization_toml_attempt_source"
						check ("source" in ('network_scan', 'legacy_backfill')),
					constraint "CHK_organization_toml_attempt_warnings"
						check (
							jsonb_typeof("warnings") = 'array' and
							"warnings" <@
								'["TlsCertificateVerificationDisabled"]'::jsonb
						)
				)
			`);
			await queryRunner.query(`
				create table if not exists "organization_toml_snapshot" (
					"organizationId" integer primary key,
					"latestAttemptObservedAt" timestamptz not null,
					"latestAttemptSequence" bigint not null,
					"latestAttemptRunId" text not null,
					"latestAttemptResult" text not null,
					"latestAttemptState" text not null,
					"latestAttemptWarnings" jsonb not null default '[]'::jsonb,
					"latestAttemptAuthoritative" boolean not null,
					"latestAttemptContentHash" char(64),
					"latestSuccessObservedAt" timestamptz,
					"latestSuccessSequence" bigint,
					"latestSuccessAuthoritative" boolean,
					"latestSuccessContentHash" char(64),
					"latestSuccessWarnings" jsonb,
					"latestFailureObservedAt" timestamptz,
					"latestFailureSequence" bigint,
					"latestFailureRunId" text,
					"latestFailureState" text,
					"latestFailureWarnings" jsonb,
					"latestFailureContentHash" char(64),
					"latestInsecureObservedAt" timestamptz,
					"latestInsecureSequence" bigint,
					"latestInsecureRunId" text,
					"latestInsecureResult" text,
					"latestInsecureState" text,
					"latestInsecureWarnings" jsonb,
					"latestInsecureContentHash" char(64),
					"createdAt" timestamptz not null default now(),
					"updatedAt" timestamptz not null default now(),
					constraint "FK_organization_toml_snapshot_organization"
						foreign key ("organizationId") references "organization"(id)
						on delete cascade,
					constraint "FK_organization_toml_snapshot_latest_attempt"
						foreign key ("latestAttemptSequence")
						references "organization_toml_attempt"("sequence"),
					constraint "FK_organization_toml_snapshot_latest_success"
						foreign key (
							"organizationId", "latestSuccessSequence",
							"latestSuccessAuthoritative", "latestSuccessObservedAt",
							"latestSuccessContentHash"
						) references "organization_toml_attempt"(
							"organizationId", "sequence", "authoritative",
							"observedAt", "contentHash"
						),
					constraint "FK_organization_toml_snapshot_latest_failure"
						foreign key ("latestFailureSequence")
						references "organization_toml_attempt"("sequence"),
					constraint "FK_organization_toml_snapshot_latest_insecure"
						foreign key ("latestInsecureSequence")
						references "organization_toml_attempt"("sequence"),
					constraint "FK_organization_toml_snapshot_attempt_content"
						foreign key ("latestAttemptContentHash")
						references "organization_toml_content"("hash"),
					constraint "FK_organization_toml_snapshot_success_content"
						foreign key ("latestSuccessContentHash")
						references "organization_toml_content"("hash"),
					constraint "FK_organization_toml_snapshot_failure_content"
						foreign key ("latestFailureContentHash")
						references "organization_toml_content"("hash"),
					constraint "FK_organization_toml_snapshot_insecure_content"
						foreign key ("latestInsecureContentHash")
						references "organization_toml_content"("hash"),
					constraint "CHK_organization_toml_snapshot_attempt_result"
						check ("latestAttemptResult" in ('success', 'failure')),
					constraint "CHK_organization_toml_snapshot_attempt_authority"
						check (
							not "latestAttemptAuthoritative" or not (
								"latestAttemptWarnings" ?
								'TlsCertificateVerificationDisabled'
							)
						),
					constraint "CHK_organization_toml_snapshot_success"
						check (
							(
								"latestSuccessSequence" is null and
								"latestSuccessObservedAt" is null and
								"latestSuccessAuthoritative" is null and
								"latestSuccessContentHash" is null and
								"latestSuccessWarnings" is null
							) or (
								"latestSuccessSequence" is not null and
								"latestSuccessObservedAt" is not null and
								"latestSuccessAuthoritative" is true and
								"latestSuccessContentHash" is not null and
								"latestSuccessWarnings" = '[]'::jsonb
							)
						)
				)
			`);
			await queryRunner.query(`
					create table if not exists "organization_toml_backfill_progress" (
					"phase" text primary key,
					"lastOrganizationId" integer,
					"completed" boolean not null default false,
					"updatedAt" timestamptz not null default now(),
					constraint "CHK_organization_toml_backfill_phase"
						check ("phase" = 'organizations')
				)
				`);
			await queryRunner.query(`
					create table if not exists "organization_toml_backfill_quarantine" (
						"organizationId" integer not null,
						"measurementTime" timestamptz not null,
						"reasonCode" text not null,
						"firstObservedAt" timestamptz not null default now(),
						"lastObservedAt" timestamptz not null default now(),
						"occurrences" integer not null default 1,
						constraint "PK_organization_toml_backfill_quarantine"
							primary key ("organizationId", "measurementTime", "reasonCode"),
						constraint "FK_organization_toml_backfill_quarantine_organization"
							foreign key ("organizationId") references "organization"(id)
							on delete cascade,
						constraint "CHK_organization_toml_backfill_quarantine_reason"
							check ("reasonCode" in ('invalid_state', 'invalid_warnings')),
						constraint "CHK_organization_toml_backfill_quarantine_occurrences"
							check ("occurrences" between 1 and 2147483647)
					)
				`);
			await queryRunner.query(`
				insert into "organization_toml_backfill_progress" ("phase")
				values ('organizations') on conflict ("phase") do nothing
			`);
			await this.ensureConcurrentIndex(
				queryRunner,
				'IDX_organization_toml_attempt_observed',
				`create index concurrently if not exists
					"IDX_organization_toml_attempt_observed"
				on "organization_toml_attempt" (
					"organizationId", "observedAt" desc, "sequence" desc
				)`
			);
		} finally {
			await queryRunner.query(`reset statement_timeout`);
			await queryRunner.query(`reset lock_timeout`);
		}
	}

	private async ensureConcurrentIndex(
		queryRunner: QueryRunner,
		indexName: string,
		createSql: string
	): Promise<void> {
		const rows = ((await queryRunner.query(
			`select index_metadata.indisvalid as "isValid"
			 from pg_class index_relation
			 join pg_namespace index_namespace
				on index_namespace.oid = index_relation.relnamespace
			 join pg_index index_metadata
				on index_metadata.indexrelid = index_relation.oid
			 where index_namespace.nspname = current_schema()
				and index_relation.relname = $1`,
			[indexName]
		)) ?? []) as Array<{ isValid: unknown }>;
		if (rows[0]?.isValid === true) return;
		if (rows.length > 0) {
			await queryRunner.query(
				`drop index concurrently if exists "${indexName}"`
			);
		}
		await queryRunner.query(createSql);
	}

	public async down(queryRunner: QueryRunner): Promise<void> {
		await queryRunner.query(`set lock_timeout = '2s'`);
		try {
			await queryRunner.query(`
				drop table if exists "organization_toml_backfill_quarantine"
			`);
			await queryRunner.query(`
				drop table if exists "organization_toml_backfill_progress"
			`);
			await queryRunner.query(
				`drop table if exists "organization_toml_snapshot"`
			);
			await queryRunner.query(
				`drop table if exists "organization_toml_attempt"`
			);
			await queryRunner.query(
				`drop table if exists "organization_toml_content"`
			);
			await queryRunner.query(`
				alter table "organization_measurement"
					drop constraint if exists
						"CHK_organization_measurement_toml_fetch_result",
					drop column if exists "scanRunId",
					drop column if exists "tomlEvidenceSequence",
					drop column if exists "tomlFetchResult"
			`);
		} finally {
			await queryRunner.query(`reset lock_timeout`);
		}
	}
}
